"""empty message

Revision ID: 6631bcde905d
Revises: 5289f48184ee
Create Date: 2023-04-12 02:12:41.500440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6631bcde905d'
down_revision = '5289f48184ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=80), nullable=True))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
